<?php

/*----------------------------------------------------------------------------------------------------------
  LOAD THE MAIN THEME FUNCTION FILES - WARNING: PLEASE DO NOT EDIT THIS FILE IN ANY WAY!
-----------------------------------------------------------------------------------------------------------*/

// If this file is called directly, busted!
if( !defined( 'ABSPATH' ) ) {
  exit;
}



$template_directory = get_template_directory();

// Basic theme functionality
require $template_directory . '/includes/functions.php';

// Theme Initialization
require $template_directory . '/includes/funtions-init.php';

// Theme hooks through Gameleon own functions.
require $template_directory . '/includes/tha-theme-hooks.php';

// Theme hooks
require $template_directory . '/includes/hooks.php';

// Post Views Counter
require $template_directory . '/includes/post-views-count.php';

// Register sidebar widgets
require $template_directory . '/includes/functions-sidebar.php';

// MyArcadePlugin Api
require $template_directory . '/includes/myarcadeplugin_api.php';

// Responsive Adsense Ads
require $template_directory . '/includes/td-ads.php';

// Theme version
require $template_directory . '/includes/version.php';

// Import demo
require $template_directory . '/includes/oneclick/import-demo-files.php';

// Theme customizer
require $template_directory . '/includes/customizer/controls.php';
require $template_directory . '/includes/customizer/css.php';
require $template_directory . '/includes/customizer/sanitize.php';
require $template_directory . '/includes/customizer/settings.php';


// Load without condition check, mashshare file contain functions that have to be loaded even if plugin is not activated
require( $template_directory . '/includes/mashsharer.php' );

